language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0
  - ruby-head
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -qq --force-yes gcc-multilib g++-multilib
  - gem update --system
  - gem install bundler
  - gem --version
